//
//  UIColor+gamepoll.swift
//
//  Generated by Zeplin on 1/24/16.
//  Copyright (c) 2016 __MyCompanyName__. All rights reserved.
//

import UIKit

extension UIColor {
    class func gmpBackgroundBlackColor() -> UIColor {
        return UIColor(red: 55.0 / 255.0, green: 54.0 / 255.0, blue: 54.0 / 255.0, alpha: 1.0)
    }

    class func gmpButtonGreenColor() -> UIColor {
        return UIColor(red: 73.0 / 255.0, green: 243.0 / 255.0, blue: 102.0 / 255.0, alpha: 1.0)
    }

    class func gmpButtonRedColor() -> UIColor {
        return UIColor(red: 254.0 / 255.0, green: 40.0 / 255.0, blue: 81.0 / 255.0, alpha: 1.0)
    }

    class func gmpDarkTextColor() -> UIColor {
        return UIColor(white: 74.0 / 255.0, alpha: 1.0)
    }

    class func gmpButtonWhiteColor() -> UIColor {
        return UIColor(white: 255.0 / 255.0, alpha: 1.0)
    }

    class func gmpButtonWhiteShadowColor() -> UIColor {
        return UIColor(white: 0.0, alpha: 0.32)
    }

    class func gmpQuestionCardGreyColor() -> UIColor {
        return UIColor(red: 239.0 / 255.0, green: 239.0 / 255.0, blue: 244.0 / 255.0, alpha: 1.0)
    }

    class func gmpWhiteTextColor() -> UIColor {
        return UIColor(white: 249.0 / 255.0, alpha: 1.0)
    }
}
